"""Protocolos para repositorios (Ports)"""

from typing import List, Optional, Protocol
from domain.modelos.item import Item


class ItensRepositoryProtocol(Protocol):
    def buscar_por_id(self, item_id: str) -> Optional[Item]: ...
    def buscar_por_descriptor(self, descritor: str) -> List[Item]: ...
    def buscar_por_ano(self, ano: str) -> List[Item]: ...
    def buscar_por_disciplina(self, disciplina: str) -> List[Item]: ...
    def sortear_questoes(self, descritores: List[str], quantidade: int) -> List[Item]: ...
    def atualizar_item(self, item: Item) -> bool: ...
    def registrar_aplicacao(self, item_id: str, acertou: bool) -> None: ...
    def listar_todos(self) -> List[Item]: ...
