name: Sync to Hugging Face

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Push to Hugging Face
        run: |
          git remote add hf https://lucimaralberti:${{ secrets.HF_TOKEN }}@huggingface.co/spaces/lucimaralberti/sistemalados
          git push hf main --force
